config/routes.rb
Rails.application.routes.draw do

  root  "woofs#index"
  get   "woofs/:id",  to: "woofs#show",     as: :woof
  post  "/",          to: "woofs#create",   as: :woof_create

end

app/models/woof.rb
class Woof < ActiveRecord::Base
  validates :body, presence: true
  validates :body, length: { maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/woofs_controller.rb
class WoofsController < ApplicationController

  def index
    find_all
  end

  def show
    @woof = Woof.find(params[:id])
  end

  def create
    @woof = Woof.new(woof_params)
    if @woof.save
      redirect_to root_path
    else
      find_all
      render :index
    end
  end

  private

    def find_all
      @woofs = Woof.all
    end

    def woof_params
      params.require(:woof).permit(:author, :body)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Woofer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/woofs/index.html.erb
<% @woofs.each do |woof| %>
  <a href= <%= woof_path(woof.id) %> style="display: block">
  <div style="border-style: solid; width: 30%; padding: 10px">
    <blockquote><%= woof.body %></blockquote>
    <cite>--sez <%= woof.author %> at <%= woof.created_at %></cite>
  </div></a><br>
<% end %>

<%= form_for :woof, url: woof_create_path do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %><br><br>
  <%= f.label :body %>
  <%= f.text_area :body %><br>
  <%= f.submit "WOOF" %>
<% end %>

app/views/woofs/show.html.erb
<div style="border-style: solid; width: 30%; padding: 10px">
  <blockquote><%= @woof.body %></blockquote>
  <cite>--sez <%= @woof.author %> at <%= @woof.created_at %></cite>
</div>